#!/usr/bin/env bash
#name $input as the first arugment sent to script
input="/Users/medialab/Google_Drive/05_DriveContents_TXT/_old/"
echo input is $input
#set $target to filename of $input
#by getting basename of $input
target="${input##*/}"
echo target is "$target"
