#!/usr/bin/env bash

BIWhite='\e[1;97m'
BIRed='\e[1;91m'
Color_Off='\e[0m'

	echo -e "${BIWhite}"Please enter DPX Object ID Number with underscores:"${Color_Off}"
	echo -e "${BIWhite}"ex. 2015_167_10_1"${Color_Off}"
	read DPXID

	echo -e "${BIWhite}"Please enter DPX Object Title with underscores:"${Color_Off}"
	echo -e "${BIWhite}"ex. Juke_Joint"${Color_Off}"
	read TITLE

	echo -e "${BIWhite}"Please enter destination for directory tree to be created:"${Color_Off}"
	read DEST

	DESTINATION=("${DEST}"/"${DPXID}"__"${TITLE}")
	mkdir "${DEST}"/"${DPXID}"__"${TITLE}"
	
	mkdir "${DESTINATION}"/"${DPXID}"__"${TITLE}"_R1

	AUDR1=("${DESTINATION}"/"${DPXID}"__"${TITLE}"_R1/"${DPXID}"__"${TITLE}"_R1_Audio)
	mkdir "${DESTINATION}"/"${DPXID}"__"${TITLE}"_R1/"${DPXID}"__"${TITLE}"_R1_Audio

	DERR1=("${DESTINATION}"/"${DPXID}"__"${TITLE}"_R1/"${DPXID}"__"${TITLE}"_R1_Derivatives)
	mkdir "${DESTINATION}"/"${DPXID}"__"${TITLE}"_R1/"${DPXID}"__"${TITLE}"_R1_Derivatives
	
	DPXR1=("${DESTINATION}"/"${DPXID}"__"${TITLE}"_R1/"${DPXID}"__"${TITLE}"_R1_DPX)
	mkdir "${DESTINATION}"/"${DPXID}"__"${TITLE}"_R1/"${DPXID}"__"${TITLE}"_R1_DPX

	mkdir "${DESTINATION}"/"${DPXID}"__"${TITLE}"_R2

	AUDR2=("${DESTINATION}"/"${DPXID}"__"${TITLE}"_R2/"${DPXID}"__"${TITLE}"_R2_Audio)
	mkdir "${DESTINATION}"/"${DPXID}"__"${TITLE}"_R2/"${DPXID}"__"${TITLE}"_R2_Audio

	DERR2=("${DESTINATION}"/"${DPXID}"__"${TITLE}"_R2/"${DPXID}"__"${TITLE}"_R2_Derivatives)
	mkdir "${DESTINATION}"/"${DPXID}"__"${TITLE}"_R2/"${DPXID}"__"${TITLE}"_R2_Derivatives
	
	DPXR2=("${DESTINATION}"/"${DPXID}"__"${TITLE}"_R2/"${DPXID}"__"${TITLE}"_R2_DPX)
	mkdir "${DESTINATION}"/"${DPXID}"__"${TITLE}"_R2/"${DPXID}"__"${TITLE}"_R2_DPX


	echo -e "${BIWhite}"Please enter directory to be worked with:"${Color_Off}"
	read INPUT
	echo
	echo -e "${BIWhite}"Moving files from "${INPUT}" "${Color_Off}"

	find "${INPUT}" -name "*R1*.wav" -exec mv -vi {} "${AUDR1}" \;
	find "${INPUT}" -name "*R1*.mov" -exec mv -vi {} "${DERR1}" \;
	find "${INPUT}" -name "*R1*.dpx" -exec mv -vi {} "${DPXR1}" \;

	find "${INPUT}" -name "*R2*.wav" -exec mv -vi {} "${AUDR2}" \;
	find "${INPUT}" -name "*R2*.mov" -exec mv -vi {} "${DERR2}" \;
	find "${INPUT}" -name "*R2*.dpx" -exec mv -vi {} "${DPXR2}" \;

	echo
	echo -e "${BIWhite}"Removing "${INPUT}" "${Color_Off}"
	rm -vri "${INPUT}"

	find "${DESTINATION}" -name "*R1*.wav" -exec mv -vi {} "${AUDR1}"/"${DPXID}"_R1_AUD.wav \;
	find "${DESTINATION}" -name "*R1*ProResHQ*.mov" -exec mv -vi {} "${DERR1}"/"${DPXID}"_R1_DER_01.mov \;
	find "${DESTINATION}" -name "*R1*Uncompressed*.mov" -exec mv -vi {} "${DERR1}"/"${DPXID}"_R1_DER_02.mov \;
	find "${DESTINATION}" -name "*R2*.wav" -exec mv -vi {} "${AUDR2}"/"${DPXID}"_R2_AUD.wav \;
	find "${DESTINATION}" -name "*R2*ProResHQ*.mov" -exec mv -vi {} "${DERR2}"/"${DPXID}"_R2_DER_01.mov \;
	find "${DESTINATION}" -name "*R2*Uncompressed*.mov" -exec mv -vi {} "${DERR2}"/"${DPXID}"_R2_DER_02.mov \;