#!/usr/bin/env bash

#a script to create a directory structure for NMAAHC Great Migration appointments

### CONSTANTS

date="$(date +%Y%m%d)"
biwhite=$(tput bold)$(tput setaf 7)
bired=$(tput bold)$(tput setaf 1)
color_off=$(tput sgr0)
