#!/usr/bin/env bash

DATE="$(date +%Y%m%d)"

while [ "${*}" != "" ] ; do

	#set $DRIVE as the first arugment sent to script
	DRIVE="${1}"
  OUTPUT="/Users/medialab/Desktop/05_DriveContents_TXT/"${DRIVE}"_contents_"${DATE}".txt"
	touch "${OUTPUT}"
	tree -I "*.dpx" -h --du -U "${DRIVE}" >> "${OUTPUT}"

#	if ?=0; then
#			echo 'done. moving to next drive.'
#		else
#			echo 'error'
#	fi

	shift

done
