#!/usr/bin/env bash

# create Great Migration directory structur as set in gmconfig

### CONSTANTS
TODAY=$(date +"%Y%m%d")
DATE=$(date +"%Y-%m-%d")

script_path=${0%/*}
# script_path will be the directory path of {0} which is the script being called
. "$script_path/nmaahcmmfunctions"
# You can't directly call a function in another shell script.
# You can move your function definitions into a separate file and then load them into your script using the . command, like this:
# . /path/to/functions.sh
# This will interpret functions.sh as if it's content were actually present in your file at this point.
# This is a common mechanism for implementing shared libraries of shell functions.
[[ -f "$script_path/nmaahcmmfunctions" ]] || { echo "Missing '$script_path/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
# will check to see that that nmaahcmmfunctions exists and if it doesn't (left side of || exits non-zero) then it will execute the right side of ||

### FUNCTIONS

_makenotes(){
    mkdir -p "${GM_DIR}/${FORMAT}/ACCESS"
    mkdir -p "${GM_DIR}/${FORMAT}/PRESERVATION"
    NOTES="${GM_DIR}/${FORMAT}/${TODAY}_${GM_PROFILE_LAST}_${GM_PROFILE_FIRST}_${FORMAT}_Notes.txt"
    touch "${NOTES}"
    if [[ "${CARRIER}" == "FILM" ]] ; then
        echo "These are notes concerning the ${FORMAT} films of ${GM_PROFILE_FIRST} ${GM_PROFILE_LAST} which were scanned on ${DATE} by the operator ${GM_OPERATOR}. They cover technical and preservation concerns of the films, noted by the operator at the time of initial inspection and scanning, not content of the films." >> "${NOTES}"
    elif [[ "${CARRIER}" == "TAPE" ]] ; then
        echo "These are notes concerning the ${FORMAT} tapes of ${GM_PROFILE_FIRST} ${GM_PROFILE_LAST} which were digitized on ${DATE} by the operator ${GM_OPERATOR}. They cover technical and preservation concerns of the tapes, noted by the operator at the time of initial inspection and digitization, not content of the tapes." >> "${NOTES}"
    fi
}

makegm (){
    GM_DIR="${GM_DIR}/${TODAY}_${GM_PROFILE_LAST}_${GM_PROFILE_FIRST}"
    mkdir -p "${GM_DIR}"
    GENERAL_NOTES="${GM_DIR}/${TODAY}_${GM_PROFILE_LAST}_${GM_PROFILE_FIRST}_generalNotes.txt"
    touch "${GENERAL_NOTES}"
    echo "These are general notes concerning the appointment of ${GM_PROFILE_FIRST} ${GM_PROFILE_LAST} on ${DATE}. They were written by the operator, ${GM_OPERATOR}, and contain observations about the appointment and information relayed by ${GM_PROFILE_FIRST} ${GM_PROFILE_LAST}." >> "${GENERAL_NOTES}"

    #35mm
    if [ "${GM_FORMATS_35MM}" = "1" ] ; then
        FORMAT="35mm"
        CARRIER="FILM"
        _makenotes
    fi
    #16mm
    if [ "${GM_FORMATS_16MM}" = "1" ] ; then
        FORMAT="16mm"
        CARRIER="FILM"
        _makenotes
    fi
    #Regular 8
    if [ "${GM_FORMATS_R8}" = "1" ] ; then
        FORMAT="Regular8mm"
        CARRIER="FILM"
        _makenotes
    fi
    #Super 8
    if [ "${GM_FORMATS_S8}" = "1" ] ; then
        FORMAT="Super8"
        CARRIER="FILM"
        _makenotes
    fi
    #VHS
    if [ "${GM_FORMATS_VHS}" = "1" ] ; then
        FORMAT="VHS"
        CARRIER="TAPE"
        _makenotes
    fi
    #MiniDV
    if [ "${GM_FORMATS_MINIDV}" = "1" ] ; then
        FORMAT="MiniDV"
        CARRIER="TAPE"
        _makenotes
    fi
    #Video8
    if [ "${GM_FORMATS_V8}" = "1" ] ; then
        FORMAT="Video8"
        CARRIER="TAPE"
        _makenotes
    fi
    #Hi8
    if [ "${GM_FORMATS_HI8}" = "1" ] ; then
        FORMAT="Hi8"
        CARRIER="TAPE"
        _makenotes
    fi
    #Digital8
    if [ "${GM_FORMATS_D8}" = "1" ] ; then
        FORMAT="Digital8"
        CARRIER="TAPE"
        _makenotes
    fi
    #U-matic
    if [ "${GM_FORMATS_UMATIC}" = "1" ] ; then
        FORMAT="Umatic"
        CARRIER="TAPE"
        _makenotes
    fi
    #Betacam
    if [ "${GM_FORMATS_BETA}" = "1" ] ; then
        FORMAT="Betacam"
        CARRIER="TAPE"
        _makenotes
    fi
    #BetacamSP
    if [ "${GM_FORMATS_BETASP}" = "1" ] ; then
        FORMAT="BetacamSP"
        CARRIER="TAPE"
        _makenotes
    fi
    #DigiBeta
    if [ "${GM_FORMATS_DIGIBETA}" = "1" ] ; then
      FORMAT="DigiBeta"
      CARRIER="TAPE"
      _makenotes
    fi
    #1" Video
    if [ "${GM_FORMATS_ONEINCHVIDEO}" = "1" ] ; then
      FORMAT="OneInchVideo"
      CARRIER="TAPE"
      _makenotes
    fi
    #1/2" Video
    if [ "${GM_FORMATS_HALFINCHVIDEO}" = "1" ] ; then
      FORMAT="HalfInchVideo"
      CARRIER="TAPE"
      _makenotes
    fi
    #Compact Audio Cassette
    if [ "${GM_FORMATS_COMPACTAUDIOCASSETTE}" = "1" ] ; then
      FORMAT="AudioCassette"
      CARRIER="TAPE"
      _makenotes
    fi
    # 1/4" Open Reel Audio
    if [ "${GM_FORMATS_QUARTERINCHOPENREELAUDIO}" = "1" ] ; then
      FORMAT="QuarterInchOpenReel"
      CARRIER="TAPE"
      _makenotes
    fi
}

#call the function(s)

makegm "${@}"

exit "$?"
