#!/usr/bin/env bash

# a script to write the contents of a directory in tree form and save it to a .txt file

# load nmaahcmmfunctions into this script
script_path=${0%/*}
. "${script_path}/nmaahcmmfunctions"
[[ -f "${script_path}/nmaahcmmfunctions" ]] || { echo "Missing '${script_path}/nmaahcmmfunctions'. Exiting." ; exit 1 ;};
_setcolors # assigns colors using a function defined in nmaahcmmfunctions
_initialize_make # safe script termination process defined in nmaahcmmfunctions

### USAGE

usage(){
    echo
    echo "$(basename "${0}")"
    echo "This application will write the contents of a directory in tree form and save it to a .txt file. It takes one or more directories as input."
    echo "Usage: $(basename ${0}) /path/to/directory1 [ /path/to/directory2 ... ] "
    echo
    exit
}
[ "${#}" = 0 ] && usage # if the the command is run with no arguments then usage is called
# if the operator runs "[scriptname] -h" then the usage text above will display in the terminal
OPTIND=1
while getopts ":h" OPT; do
    case "${OPT}" in
        h) usage ;;
    esac
done
shift $(( ${OPTIND} - 1 ))

### FUNCTIONS

makedrivetree(){
local drive ; #set local variable $drive
local folder=/Volumes/UtilitySAN/05_driveContents
for drive ; do
    drive="${drive%/}" #strip trailing / if any
    if [ -d "${drive}" ] ; then
        output="${drive##*/}_contents_${date}.txt"
        output="${folder}/${output}"
            if [ -d "${folder}" ] ; then
                tree --filelimit 50 --si --du -U -Q -o "${output}" "${drive}"
                if grep "0 directories, 0 files" "${output}" ; then
                    printf "%s%s is empty. Adding EMPTY to file name.\n%s" "${biwhite}" "${drive}" "${color_off}" && outputE="${folder}/${drive##*/}_contents_${date}_EMPTY.txt" && mv -v "${output}" "${output}E"
                    printf "%sMoving %s to %s\n%s" "${biwhite}" "${outputE##*/}" "${drive}" "${color_off}"
                    cp -v "${outputE}" "${drive}"
                else
                    printf "%s%s is not empty\n%s" "${biwhite}" "${drive}" "${color_off}"
                    cp -va "${output}" "${drive}"
                fi
            else
                printf "%sError %s does not exist. Exiting.\n" "${bired}" "${folder}" >&2
                exit
            fi
    else
        printf "%sError %s does not exist. Exiting.\n" "${bired}" "${drive}" >&2
        exit
    fi
    
  done
}

#call the function(s)

makedrivetree "${@}"

exit "$?"
