#!/usr/bin/env bash

#a script to create md5 checksums of all files in a directory or a single file and save it to a .md5 file

### CONSTANTS

color_off='\e[0m'
biwhite='\e[1;97m'
date="$(date +%Y%m%d)"

### FUNCTIONS

makechecksum ()

{
while [ "${*}" != "" ] ; do

	#name $input as the first arugment sent to script
	input="${1}"

	#name target as the filename of $input
	target=$(basename "${input}")

	#if argment is a directory, run md5deep
	if [ -d "${input}" ] ; then
		#set .md5 file to $output
		output="${input}"/"${target}_${date}_checksums.md5"
		echo -e "${biwhite}""${target}" 'is a directory, making checksum of all files in' "${target}"	"${color_off}"
		md5deep -bre "${input}" >> "${output}"
	fi

	#if argment is a file, run md5deep
	if [ -f "${input}" ] ; then
		#set .md5 file to $output
		output=$(dirname "${input}")/"${target}_${date}_checksums.md5"
		echo -e "${biwhite}""${target}" 'is a file, making checksum of' "${target}" 'in' "${output}" "${color_off}"
		md5deep -bre "${input}" >> "${output}"
	fi

	#sort $output
	echo
	echo -e "${biwhite}"'Sorting' $(basename "${output}")
	sort -k 2 -o "${output}" "${output}"
	echo
	echo -e 'Finished making checksums for' "${input}". 'Moving to next job.'"${color_off}"

	shift
done
}

#call the function(s)

makechecksum "@"

exit $?
