#!/usr/bin/env bash

# a script to copy .md5 checksum files and the first .dpx file in a stack to a designated directory

### CONSTANTS

biwhite=$(tput bold)$(tput setaf 7)
bired=$(tput bold)$(tput setaf 1)
color_off=$(tput sgr0)

### FUNCTIONS

moveDPX ()
{
	while [ "${*}" != "" ] ; do

		dpx_folder="${1}"
		target_folder="/Users/medialab/Google_Drive/07_DPX_checksums/${dpx_folder##*/}"
		mkdir -p "$target_folder"

		if [ ! -d "$target_folder" ] ; then
			printf "%sCreating %s" "$biwhite" "$target_folder"
		fi

		for file in "$dpx_folder"/*DPX*/* ; do
			if [ -f "$target_folder"/*.dpx ] ; then
				printf "%s%s exists, verifying checksum" "$biwhite" "${file##*/}"
				rsync -aPhic "$file" "$target_folder"
				rsync_err_1="$?"
			else
				rsync -aPhi "$file" "$target_folder"
				rsync_err_1="$?"
			fi
			printf "%srsync exit status is: %s" "$biwhite" "$rsync_err_1"

			if [[ "$rsync_err_1" == 0 ]]; then
				#statements
				printf "%sMOVED: %s" "$biwhite" "${file##*/}"
			        printf "%sTO DIRECTORY: %s" "$biwhite" "$target_folder"
			  echo
		 	else
				printf "%sERRORS" "$bired"
			fi
			break 1
		done

		for md5 in "$dpx_folder"/*.md5 ; do
			if [ -f "$target_folder"/*.md5 ] ; then
				printf "%s%s exists, verifying checksum" "$biwhite" "${md5##*/}"
				rsync -aPhic "$md5" "$target_folder"
				rsync_err_2="$?"
			else
				rsync -aPhi "$md5" "$target_folder"
				rsync_err_2="$?"
			fi
				printf "%srsync exit status is: %s" "$biwhite" "$rsync_err_2"

		 	if [[ "$rsync_err_2" == 0 ]] ; then
		 		#statements
				printf "%sMOVED: %s" "$biwhite" "${md5##*/}"
				printf "%sTO DIRECTORY: %s" "$biwhite" "$target_folder"
				echo
			else
				printf "%sERRORS" "$bired"
			fi
		done
		printf "moving on"
		shift

	done
	echo
	chmod_folder="/Users/medialab/Desktop/07_DPX_checksums"
	printf "%schanged permissions on the following files in directory %s to 777:" "$biwhite" "${chmod_folder##*/}"
	chmod -vR 777 "$chmod_folder"
}

#call the function(s)

moveDPX "$@"

exit "$?"
