#!/usr/bin/env bash

# a script to copy .md5 checksum files and the first .dpx file in a stack to a designated directory

### CONSTANTS

biwhite=$(tput bold)$(tput setaf 7)
bired=$(tput bold)$(tput setaf 1)
color_off=$(tput sgr0)

### FUNCTIONS

moveDPX ()
{
	while [ "${*}" != "" ] ; do

		dpx_folder="${1}"
		target_folder="/Users/medialab/Google_Drive/07_DPX_checksums/${dpx_folder##*/}"
		mkdir -p "$target_folder"

		if [ ! -d "$target_folder" ] ; then
			printf "Creating:\t%s%s%s\n" "$biwhite" "$target_folder" "$color_off"
		fi

		for file in "$dpx_folder"/*DPX*/* ; do
			if [ -f "$target_folder"/*.dpx ] ; then
				printf "%s%s% exists, verifying checksum.\n" "$biwhite" "${file##*/}" "$color_off"
				rsync -aPhic "$file" "$target_folder"
				rsync_err_1="$?"
			else
				rsync -aPhi "$file" "$target_folder"
				rsync_err_1="$?"
			fi
			printf "%srsync exit status is: %s%s\n" "$biwhite" "$rsync_err_1" "$color_off"

			if [[ "$rsync_err_1" == 0 ]]; then
				printf "MOVED:\t%s%s%s\nTO DIRECTORY:\t%s%s%s\n" "$biwhite" "${file##*/}" "$color_off" "$biwhite" "$target_folder" "$color_off"
			  echo
		 	else
				printf "%sERRORS%s\n" "$bired" "$color_off"
			fi
			break 1
		done

		for md5 in "$dpx_folder"/*.md5 ; do
			if [ -f "$target_folder"/*.md5 ] ; then
				printf "%s%s%s exists, verifying checksum." "$biwhite" "${md5##*/}" "$color_off"
				rsync -aPhic "$md5" "$target_folder"
				rsync_err_2="$?"
			else
				rsync -aPhi "$md5" "$target_folder"
				rsync_err_2="$?"
			fi
				printf "%srsync exit status is: %s%s" "$biwhite" "$rsync_err_2" "$color_off"

		 	if [[ "$rsync_err_2" == 0 ]] ; then
				printf "MOVED:\t%s%s%s\nTO DIRECTORY:\t%s%s%s\n" "$biwhite" "${md5##*/}" "$color_off" "$biwhite" "$target_folder" "$color_off"
				echo
			else
				printf "%sERRORS\n" "$bired" "$color_off"
			fi
		done
		printf "moving on"
		shift

	done
	echo
	chmod_folder="$HOME/Google_Drive/07_DPX_checksums"
	printf "%schanged permissions on the following files in directory %s to 777:%s" "$biwhite" "${chmod_folder##*/}" "$color_off"
	chmod -vR 777 "$chmod_folder"
}

#call the function(s)

moveDPX "$@"

exit "$?"
