#!/usr/bin/env bash

#a script to create a the desired directory structure and filenames for DPX packages received from VFS

### CONSTANTS

biwhite='\e[1;97m'
bired='\e[1;91m'
color_off='\e[0m'

### FUNCTIONS

restructureDPX ()

{
printf "${biwhite}"'Please enter the number of reels your DPX package has: '

read reelnumber

case "$reelnumber" in
	1 )
	printf "${biwhite}"'Please enter DPX Object ID Number with underscores:'"${color_off}"
	printf "${biwhite}"'ex. 2015_167_10_1'"${color_off}"
	read dpxid

	printf "${biwhite}"Please enter DPX Object title with underscores:"${color_off}"
	printf "${biwhite}"ex. Juke_Joint"${color_off}"
	read title

	printf "${biwhite}"Please enter destination for directory tree to be created:"${color_off}"
	read dest

	destination=("${dest}"/"${dpxid}"__"${title}")
	mkdir "${dest}"/"${dpxid}"__"${title}"

	mkdir "${destination}"/"${dpxid}"__"${title}"

	aud=("${destination}"/"${dpxid}"__"${title}"/"${dpxid}"__"${title}"_Audio)
	mkdir "${destination}"/"${dpxid}"__"${title}"/"${dpxid}"__"${title}"_Audio

	der=("${destination}"/"${dpxid}"__"${title}"/"${dpxid}"__"${title}"_Derivatives)
	mkdir "${destination}"/"${dpxid}"__"${title}"/"${dpxid}"__"${title}"_Derivatives

	dpx=("${destination}"/"${dpxid}"__"${title}"/"${dpxid}"__"${title}"_DPX)
	mkdir "${destination}"/"${dpxid}"__"${title}"/"${dpxid}"__"${title}"_DPX

	printf "${biwhite}"Please enter directory to be worked with:"${color_off}"
	read input
	echo
	printf "${biwhite}"Moving files from "${input}" "${color_off}"

	find "${input}" -name "*.wav" -exec mv -vi {} "${aud}" \;
	find "${input}" -name "*.mov" -exec mv -vi {} "${der}" \;
	find "${input}" -name "*.dpx" -exec mv -vi {} "${dpx}" \;

	echo
	printf "${biwhite}"Removing "${input}" "${color_off}"
	rm -vri "${input}"

	find "${destination}" -name "*.wav" -exec mv -vi {} "${aud}"/"${dpxid}"_AUD.wav \;
	find "${destination}" -name "*ProResHQ*.mov" -exec mv -vi {} "${der}"/"${dpxid}"_DER_01.mov \;
	find "${destination}" -name "*Uncompressed*.mov" -exec mv -vi {} "${der}"/"${dpxid}"_DER_02.mov \;
	;;

	2 )
	printf "${biwhite}"Please enter DPX Object ID Number with underscores:"${color_off}"
	printf "${biwhite}"ex. 2015_167_10_1"${color_off}"
	read dpxid

	printf "${biwhite}"Please enter DPX Object title with underscores:"${color_off}"
	printf "${biwhite}"ex. Juke_Joint"${color_off}"
	read title

	printf "${biwhite}"Please enter destination for directory tree to be created:"${color_off}"
	read dest

	destination=("${dest}"/"${dpxid}"__"${title}")
	mkdir "${dest}"/"${dpxid}"__"${title}"

	mkdir "${destination}"/"${dpxid}"__"${title}"_R1

	audR1=("${destination}"/"${dpxid}"__"${title}"_R1/"${dpxid}"__"${title}"_R1_Audio)
	mkdir "${destination}"/"${dpxid}"__"${title}"_R1/"${dpxid}"__"${title}"_R1_Audio

	DERR1=("${destination}"/"${dpxid}"__"${title}"_R1/"${dpxid}"__"${title}"_R1_Derivatives)
	mkdir "${destination}"/"${dpxid}"__"${title}"_R1/"${dpxid}"__"${title}"_R1_Derivatives

	DPXR1=("${destination}"/"${dpxid}"__"${title}"_R1/"${dpxid}"__"${title}"_R1_DPX)
	mkdir "${destination}"/"${dpxid}"__"${title}"_R1/"${dpxid}"__"${title}"_R1_DPX

	mkdir "${destination}"/"${dpxid}"__"${title}"_R2

	audR2=("${destination}"/"${dpxid}"__"${title}"_R2/"${dpxid}"__"${title}"_R2_Audio)
	mkdir "${destination}"/"${dpxid}"__"${title}"_R2/"${dpxid}"__"${title}"_R2_Audio

	derR2=("${destination}"/"${dpxid}"__"${title}"_R2/"${dpxid}"__"${title}"_R2_Derivatives)
	mkdir "${destination}"/"${dpxid}"__"${title}"_R2/"${dpxid}"__"${title}"_R2_Derivatives

	dpxR2=("${destination}"/"${dpxid}"__"${title}"_R2/"${dpxid}"__"${title}"_R2_DPX)
	mkdir "${destination}"/"${dpxid}"__"${title}"_R2/"${dpxid}"__"${title}"_R2_DPX


	printf "${biwhite}"Please enter directory to be worked with:"${color_off}"
	read input
	echo
	printf "${biwhite}"Moving files from "${input}" "${color_off}"
asdf
	find "${input}" -name "*R1*.wav" -exec mv -vi {} "${audR1}" \;
	find "${input}" -name "*R1*.mov" -exec mv -vi {} "${derR1}" \;
	find "${input}" -name "*R1*.dpx" -exec mv -vi {} "${dpxR1}" \;

	find "${input}" -name "*R2*.wav" -exec mv -vi {} "${audR2}" \;
	find "${input}" -name "*R2*.mov" -exec mv -vi {} "${derR2}" \;
	find "${input}" -name "*R2*.dpx" -exec mv -vi {} "${dpxR2}" \;

	echo
	printf "${biwhite}"Removing "${input}" "${color_off}"
	rm -vri "${input}"

	find "${destination}" -name "*R1*.wav" -exec mv -vi {} "${audR1}"/"${dpxid}"_R1_AUD.wav \;
	find "${destination}" -name "*R1*ProResHQ*.mov" -exec mv -vi {} "${derR1}"/"${dpxid}"_R1_DER_01.mov \;
	find "${destination}" -name "*R1*Uncompressed*.mov" -exec mv -vi {} "${derR1}"/"${dpxid}"_R1_DER_02.mov \;
	find "${destination}" -name "*R2*.wav" -exec mv -vi {} "${audR2}"/"${dpxid}"_R2_AUD.wav \;
	find "${destination}" -name "*R2*ProResHQ*.mov" -exec mv -vi {} "${derR2}"/"${dpxid}"_R2_DER_01.mov \;
	find "${destination}" -name "*R2*Uncompressed*.mov" -exec mv -vi {} "${derR2}"/"${dpxid}"_R2_DER_02.mov \;
	;;

	*	)
	printf "${bired}"ERROR. Presently, this script can only handle DPX packages of 1 or 2 reels. Sorry! Check back later."${color_off}"
	;;
esac
}

#call the function(s)

restructureDPX "$@"

exit $?
