#!/usr/bin/env bash

#a script to restructure a DPX package directory for VFCU pickup and place .md5 in driectory

### CONSTANTS

biyellow=$(tput bold)$(tput setaf 3)
bired=$(tput bold)$(tput setaf 1)
gray=$(tput setaf 7)
color_off=$(tput sgr0)
date="$(date +%Y%m%d)"

### FUNCTIONS

restrutureForVFCU ()

{
echo

for arg in "$@" ;
do
	input="$1" #name $input as the first arugment sent to script
	audio="$input/${input##*/}"__Audio
	derivatives="$input/${input##*/}"__Derivatives
	dpx="$input/${input##*/}"__DPX
	md5="/Volumes/nmaahc-borndigital/06_DPX_checksums/"

	if [ -d "$input" ] ; then
	  printf "%s%s%s is a directory.\n" "$biyellow" "$input" "$color_off"
	  printf "Moving all files in:\n\t%s%s\n\t%s%s\n\tto:\n\t%s%s%s\n" "$biyellow" "$audio" "$derivatives" "$color_off" "$biyellow" "$dpx" "$color_off"
		echo
		printf "%s" "$gray"
		if [ -d "$audio" ] ; then
	  	mv -vi "$audio"/* "$dpx" #move all file in the audio directory to the DPX directory
			rm -vri "$audio"
		fi
		if [ -d "$derivatives" ] ; then
			mv -vi "$derivatives"/* "$dpx" #move all file in the derivatives directory to the DPX directory
			rm -vri "$derivatives"
		printf "%s" "$color_off"
  else
		echo
		printf "%s%s is not a directory. Exiting" "$bired" "$input"
		exit
	fi
echo
	if [ -d "$md5" ] ; then
		printf "Moving .md5 to %s%s%s\n" "$biyellow" "$dpx" "$color_off" #place .md5 in DPX directory to initiate DPX pickup
		echo
		printf "%s" "$gray"
		rsync -avvPhi --stats "$md5/${input##*/}"/*.md5 "$dpx"
		printf "%s" "$color_off"
		echo
		printf "Done moving .md5 to %s%s%s.\nVFCU will begin picking up your files shortly." "$biyellow" "$dpx" "$color_off"
		echo
		printf "%sPlease make sure your templates have been set correctly!%s" "$bired" "$color_off"
		echo
		cowsay "Tootles!"
  else
		printf "%s%s does not exist. Exiting" "$bired" "$md5"
		exit
	fi
	shift
done
}

#call the function(s)

restrutureForVFCU "$@"

exit $?
