#!/usr/bin/env bash

#a script to restructure a DPX package directory for VFCU pickup and place .md5 in driectory

### CONSTANTS

biwhite=$(tput bold)$(tput setaf 7)
bired=$(tput bold)$(tput setaf 1)
gray=$(tput setaf 7)
color_off=$(tput sgr0)
date="$(date +%Y%m%d)"

### FUNCTIONS

restrutureForVFCU ()

{
echo

	input="$1" #name $input as the first arugment sent to script
	audio="$input/${input##*/}"__Audio
	derivatives="$input/${input##*/}"__Derivatives
	dpx="$input/${input##*/}"__DPX
	md5="/Users/medialab/Google_Drive/07_DPX_checksums/"

	if [ -d "$input" ] ; then
	  printf "%s%s%s is a directory.\n" "$biwhite" "$input" "$color_off"
	  printf "Moving all files in:\n\t%s%s\n\t%s%s\n\tto:\n\t%s%s%s\n" "$biwhite" "$audio" "$derivatives" "$color_off" "$biwhite" "$dpx" "$color_off"
		echo
		printf "%s" "$gray"
	  mv -vi "$audio"/* "$derivatives"/* "$dpx" #move all file in the audio and derivatives directories to the DPX directory
		rm -vri "$audio" "$derivatives"
		printf "%s" "$color_off"
  else
		echo
		printf "%s%s is not a directory. Exiting" "$bired" "$input"
		exit
	fi
echo
	if [ -d "$md5" ] ; then
		printf "Moving .md5 to %s%s%s\n" "$biwhite" "$dpx" "$color_off" #place .md5 in DPX directory to initiate DPX pickup
		echo
		printf "%s" "$gray"
		rsync -avvPhi --stats "$md5/${input##*/}"/*.md5 "$dpx"
		printf "%s" "$color_off"
		echo
		printf "Done moving .md5 to %s%s%s.\nVFCU will begin picking up your files shortly." "$biwhite" "$dpx" "$color_off"
		echo
		printf "%sPlease make sure your templates have been set correctly!%s" "$bired" "$color_off"
		echo
		cowsay "Tootles!"
  else
		printf "%s%s does not exist. Exiting" "$bired" "$md5"
		exit
	fi

}

#call the function(s)

restrutureForVFCU "$@"

exit $?
