#!/usr/bin/env bash

#BIWhite='\e[1;97m'
#RELATIVEPATH="access/youtube"
#SUFFIX=""
#EXTENSION="mp4"

#while [ "${*}" != "" ] ; do

	#set $INPUT as the first arugment sent to script
	INPUT="${1}"
	
	if [[ -z "${INPUT}" ]] ; then
	
	#OUTPUTDIR=$(dirname "${INPUT}")"/${RELATIVEPATH}"
    
    echo hello
    
    fi

    #echo "${OUTPUTDIR}"
    echo hello