#!/usr/bin/env bash

echo
while [ "${*}" != "" ] ; do

	INPUT="${1}"
	DPX_FOLDER="${INPUT}"
	TARGET_FOLDER="/Users/medialab/Desktop/07_DPX_checksums"/$(basename "${DPX_FOLDER}")
	mkdir -p "${TARGET_FOLDER}"
	echo
	for file in "${DPX_FOLDER}"/*DPX*/* ; do
		if [ -f "${TARGET_FOLDER}"/*.dpx ] ; then
			echo $(basename "$file") exists, verifying checksum
			rsync -aPhic "$file" "${TARGET_FOLDER}"
		else rsync -aPhi "$file" "${TARGET_FOLDER}"
		echo MOVED: $(basename "$file") 
		echo TO DIRECTORY: "${TARGET_FOLDER}"
		fi
		break 1
	done
		echo
	for md5 in "${DPX_FOLDER}"/*.md5 ; do
		if [ -f "${TARGET_FOLDER}"/*.md5 ] ; then
			echo $(basename "$md5") exists, verifying checksum
			rsync -aPhic "$md5" "${TARGET_FOLDER}"
		else
			rsync -aPhi "$md5" "${TARGET_FOLDER}" 
		echo MOVED: $(basename "$md5")
		echo TO DIRECTORY: "${TARGET_FOLDER}"
		fi
	done

	shift
	echo
	echo
	echo

done

echo changed permissions on the following files in directory $(basename "${CHMOD_FOLDER}") to 777:
CHMOD_FOLDER="/Users/medialab/Desktop/07_DPX_checksums"
chmod -vR 777 "${CHMOD_FOLDER}"