#!/usr/bin/env bash


while getopts ":o:b" OPT ; do
    case $OPT in
        o)
            echo "-o was triggered"
            ;;
        b) 
            echo "fuck me! -b was triggered"
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

 
#while getopts ":a" opt; do
#  case $opt in
#    a)
#      echo "-a was triggered!" >&2
#      ;;
#    \?)
#      echo "Invalid option: -$OPTARG" >&2
#      ;;
#  esac
#done